# @package _group_
_target_: mocasin.representations.MetricEmbeddingRepresentation
norm_p : 2
extra_dimensions : true
extra_dimensions_factor : 3
ignore_channels : true
jlt_tries : 30
disable_embedding_test : false
target_distortion : 1.2
verbose : false
