stages:
  - test

test-python3.7:
  stage: test
  image: python:3.7
  tags:
    - python3.7
  script:
  - apt-get update
  - apt-get install libblas-dev liblapack-dev
  - rm -rf pykpn/test
  - cd third_party_dependencies/pynauty-0.6
  - make pynauty
  - python setup.py install
  - cd ../..
  - python setup.py develop
  - python setup.py test

test-python3.6:
  stage: test
  image: python:3.6
  tags:
    - python3.6
  script:
  - apt-get update
  - apt-get install libblas-dev liblapack-dev
  - rm -rf pykpn/test
  - cd third_party_dependencies/pynauty-0.6
  - make pynauty
  - python setup.py install
  - cd ../..
  - python setup.py develop
  - python setup.py test
