default:
  before_script:
  - apt-get update
  - apt-get -y install libblas-dev liblapack-dev
  - ./.config_matplotlib_agg.sh

stages:
  - test

test-python3.7-develop:
  stage: test
  image: python:3.7
  tags:
    - python3.7
  script:
  - python setup.py develop
  - python setup.py test

test-python3.6-develop:
  stage: test
  image: python:3.6
  tags:
    - python3.6
  script:
  - python setup.py develop
  - python setup.py test

test-python3.7-install:
  stage: test
  image: python:3.7
  tags:
    - python3.7
  script:
  - python setup.py install
  - python setup.py test

test-python3.6-install:
  stage: test
  image: python:3.6
  tags:
    - python3.6
  script:
  - python setup.py install
  - python setup.py test
