# default:
#   before_script:
#   - apt-get update
#   - apt-get -y install libblas-dev liblapack-dev
#   - test/config_matplotlig_agg.sh

stages:
  - build_pynauty
  - build_mocasin
  - test

build-pynauty-python3.8:
  stage: build_pynauty
  image: python:3.8
  tags:
    - python3.8
  script:
    - wget -N https://web.cs.dal.ca/~peter/software/pynauty/pynauty-0.6.0.tar.gz
    - tar -xzf pynauty-0.6.0.tar.gz
    - cd pynauty-0.6.0
    - wget -N http://users.cecs.anu.edu.au/~bdm/nauty/nauty27r1.tar.gz
    - tar -xzf nauty27r1.tar.gz
    - mv nauty27r1 nauty
    - make pynauty
    - pip wheel . -w ..
  artifacts:
    paths:
      - pynauty*.whl

build-pynauty-python3.7:
  stage: build_pynauty
  image: python:3.7
  tags:
    - python3.7
  script:
    - wget -N https://web.cs.dal.ca/~peter/software/pynauty/pynauty-0.6.0.tar.gz
    - tar -xzf pynauty-0.6.0.tar.gz
    - cd pynauty-0.6.0
    - wget -N http://users.cecs.anu.edu.au/~bdm/nauty/nauty27r1.tar.gz
    - tar -xzf nauty27r1.tar.gz
    - mv nauty27r1 nauty
    - make pynauty
    - pip wheel . -w ..
  artifacts:
    paths:
      - pynauty*.whl

build-pynauty-python3.6:
  stage: build_pynauty
  image: python:3.6
  tags:
    - python3.6
  script:
    - wget -N https://web.cs.dal.ca/~peter/software/pynauty/pynauty-0.6.0.tar.gz
    - tar -xzf pynauty-0.6.0.tar.gz
    - cd pynauty-0.6.0
    - wget -N http://users.cecs.anu.edu.au/~bdm/nauty/nauty27r1.tar.gz
    - tar -xzf nauty27r1.tar.gz
    - mv nauty27r1 nauty
    - make pynauty
    - pip wheel . -w ..
  artifacts:
    paths:
      - pynauty*.whl

build-mocasin-python3.8:
  stage: build_mocasin
  image: python:3.8
  tags:
    - python3.8
  needs:
    - build-pynauty-python3.8
  variables:
    NO_PYNAUTY: 1
  script:
    - pip install pynauty*.whl
    - pip wheel --no-deps .
  artifacts:
    paths:
      - mocasin*.whl

build-mocasin-python3.7:
  stage: build_mocasin
  image: python:3.7
  tags:
    - python3.7
  needs:
    - build-pynauty-python3.7
  variables:
    NO_PYNAUTY: 1
  script:
    - pip install pynauty*.whl
    - pip wheel --no-deps .
  artifacts:
    paths:
      - mocasin*.whl

build-mocasin-python3.6:
  stage: build_mocasin
  image: python:3.6
  tags:
    - python3.6
  needs:
    - build-pynauty-python3.6
  variables:
    NO_PYNAUTY: 1
  script:
    - pip install pynauty*.whl
    - pip wheel --no-deps .
  artifacts:
    paths:
      - mocasin*.whl

test-python3.8:
  stage: test
  image: python:3.8
  tags:
    - python3.8
  needs:
    - build-pynauty-python3.8
    - build-mocasin-python3.8
  script:
    - pip install pynauty*.whl
    - pip install mocasin*.whl
    - python setup.py test

test-python3.7:
  stage: test
  image: python:3.7
  tags:
    - python3.7
  needs:
    - build-pynauty-python3.7
    - build-mocasin-python3.7
  script:
    - pip install pynauty*.whl
    - pip install mocasin*.whl
    - python setup.py test

test-python3.6:
  stage: test
  image: python:3.6
  tags:
    - python3.6
  needs:
    - build-pynauty-python3.6
    - build-mocasin-python3.6
  script:
    - pip install pynauty*.whl
    - pip install mocasin*.whl
    - python setup.py test

# test-gbm:
#   stage: test
#   variables:
#     MOCASIN_BRANCH: $CI_COMMIT_REF_NAME
#   trigger:
#     project: mocasin/mocasin-gbm
#     strategy: depend
#     branch: plugins

# test-maps-examples:
#   stage: test
#   variables:
#     MOCASIN_BRANCH: $CI_COMMIT_REF_NAME
#   trigger:
#     project: mocasin/mocasin-maps-examples
#     strategy: depend
#     branch: plugins

check-formatting:
  stage: test
  image: python:3.8
  tags:
    - python3.8
  needs: []
  script:
    - pip install black
    - black --check .
