stages:
  - test

test-python3.7:
  stage: test
  image: python:3.7
  tags:
    - python3.7
  script:
  - apt-get update
  - apt-get -y install libblas-dev liblapack-dev
  - python setup.py develop
  - python setup.py test

test-python3.6:
  stage: test
  image: python:3.6
  tags:
    - python3.6
  script:
  - apt-get update
  - apt-get -y install libblas-dev liblapack-dev
  - python setup.py develop
  - python setup.py test
