default:
  before_script:
  - apt-get update
  - apt-get -y install libblas-dev liblapack-dev
  - test/config_matplotlig_agg.sh

stages:
  - test

test-python3.8:
  stage: test
  image: python:3.8
  tags:
    - python3.8
  script:
  - pip install .
  - python setup.py test

test-python3.7:
  stage: test
  image: python:3.7
  tags:
    - python3.7
  script:
  - pip install .
  - python setup.py test

test-python3.6:
  stage: test
  image: python:3.6
  tags:
    - python3.6
  script:
  - pip install .
  - python setup.py test

test-gbm:
  stage: test
  variables:
    MOCASIN_BRANCH: $CI_COMMIT_REF_NAME
  trigger:
    project: mocasin/mocasin-gbm
    strategy: depend
    branch: plugins

check-formatting:
  stage: test
  image: python:3.8
  tags:
    - python3.8
  script:
    - pip install black
    - black --check .
