# default:
#   before_script:
#   - apt-get update
#   - apt-get -y install libblas-dev liblapack-dev
#   - test/config_matplotlig_agg.sh

stages:
  - build_pynauty
  - build_mocasin
  # - test

build-pynauty-python3.8:
  stage: build_pynauty
  image: python:3.8
  tags:
    - python3.8
  script:
    - wget -N https://web.cs.dal.ca/~peter/software/pynauty/pynauty-0.6.0.tar.gz
    - tar -xzf pynauty-0.6.0.tar.gz
    - cd pynauty-0.6.0
    - wget -N http://users.cecs.anu.edu.au/~bdm/nauty/nauty27r1.tar.gz
    - tar -xzf nauty27r1.tar.gz
    - mv nauty27r1 nauty
    - make pynauty
    - pip wheel .
  artifacts:
    paths:
      - pynauty-0.6.0/pynauty-0.6.0-cp38-cp38m-linux_x86_64.whl

build-pynauty-python3.7:
  stage: build_pynauty
  image: python:3.7
  tags:
    - python3.7
  script:
    - wget -N https://web.cs.dal.ca/~peter/software/pynauty/pynauty-0.6.0.tar.gz
    - tar -xzf pynauty-0.6.0.tar.gz
    - cd pynauty-0.6.0
    - wget -N http://users.cecs.anu.edu.au/~bdm/nauty/nauty27r1.tar.gz
    - tar -xzf nauty27r1.tar.gz
    - mv nauty27r1 nauty
    - make pynauty
    - pip wheel .
  artifacts:
    paths:
      - pynauty-0.6.0/pynauty-0.6.0-cp37-cp37m-linux_x86_64.whl

build-pynauty-python3.6:
  stage: build_pynauty
  image: python:3.6
  tags:
    - python3.6
  script:
    - wget -N https://web.cs.dal.ca/~peter/software/pynauty/pynauty-0.6.0.tar.gz
    - tar -xzf pynauty-0.6.0.tar.gz
    - cd pynauty-0.6.0
    - wget -N http://users.cecs.anu.edu.au/~bdm/nauty/nauty27r1.tar.gz
    - tar -xzf nauty27r1.tar.gz
    - mv nauty27r1 nauty
    - make pynauty
    - pip wheel .
  artifacts:
    paths:
      - pynauty-0.6.0/pynauty-0.6.0-cp36-cp36m-linux_x86_64.whl

build-mocasin-python3.8:
  stage: build_mocasin
  image: python:3.8
  tags:
    - python3.8
  dependencies:
    - build-pynauty-python3.8
  script:
    - pip install pynauty-0.6.0/pynauty-0.6.0-cp38-cp38m-linux_x86_64.whl
    - pip wheel . -w wheels
  artifacts:
    paths:
      - wheels

build-mocasin-python3.7:
  stage: build_mocasin
  image: python:3.7
  tags:
    - python3.7
  dependencies:
    - build-pynauty-python3.7
  script:
    - pip install pynauty-0.6.0/pynauty-0.6.0-cp37-cp37m-linux_x86_64.whl
    - pip wheel . -w wheels
  artifacts:
    paths:
      - wheels

build-mocasin-python3.6:
  stage: build_mocasin
  image: python:3.6
  tags:
    - python3.6
  dependencies:
    - build-pynauty-python3.6
  script:
    - pip install pynauty-0.6.0/pynauty-0.6.0-cp36-cp36m-linux_x86_64.whl
    - pip wheel . -w wheels
  artifacts:
    paths:
      - wheels

# test-python3.8:
#   stage: test
#   image: python:3.8
#   tags:
#     - python3.8
#   script:
#   - pip install .
#   - python setup.py test

# test-python3.7:
#   stage: test
#   image: python:3.7
#   tags:
#     - python3.7
#   script:
#   - pip install .
#   - python setup.py test

# test-python3.6:
#   stage: test
#   image: python:3.6
#   tags:
#     - python3.6
#   script:
#   - pip install .
#   - python setup.py test

# test-gbm:
#   stage: test
#   variables:
#     MOCASIN_BRANCH: $CI_COMMIT_REF_NAME
#   trigger:
#     project: mocasin/mocasin-gbm
#     strategy: depend
#     branch: plugins

# test-maps-examples:
#   stage: test
#   variables:
#     MOCASIN_BRANCH: $CI_COMMIT_REF_NAME
#   trigger:
#     project: mocasin/mocasin-maps-examples
#     strategy: depend
#     branch: plugins

# check-formatting:
#   stage: test
#   image: python:3.8
#   tags:
#     - python3.8
#   script:
#     - pip install black
#     - black --check .
