stages:
  - build
  - test
  - plugins

.build:
  script:
    - pip wheel -w wheels .
  artifacts:
    paths:
      - wheels

build-python3.9:
  extends: .build
  stage: build
  image: python:3.9
  tags:
    - python3.9

build-python3.8:
  extends: .build
  stage: build
  image: python:3.8
  tags:
    - python3.8

build-python3.7:
  extends: .build
  stage: build
  image: python:3.7
  tags:
    - python3.7

build-python3.6:
  extends: .build
  stage: build
  image: python:3.6
  tags:
    - python3.6

.test:
  script:
    - pip install mocasin --no-index --find-links=./wheels
    - python setup.py test

test-python3.9:
  extends: .test
  stage: test
  image: python:3.9
  tags:
    - python3.9
  needs:
    - build-python3.9

test-python3.8:
  extends: .test
  stage: test
  image: python:3.8
  tags:
    - python3.8
  needs:
    - build-python3.8

test-python3.7:
  extends: .test
  stage: test
  image: python:3.7
  tags:
    - python3.7
  needs:
    - build-python3.7

test-python3.6:
  extends: .test
  stage: test
  image: python:3.6
  tags:
    - python3.6
  needs:
    - build-python3.6

test-gbm:
  stage: plugins
  variables:
    MOCASIN_BRANCH: $CI_COMMIT_REF_NAME
  needs:
    - build-python3.9
    - build-python3.8
    - build-python3.7
    - build-python3.6
  trigger:
    project: mocasin/mocasin-gbm
    strategy: depend

test-maps-examples:
  stage: plugins
  variables:
    MOCASIN_BRANCH: $CI_COMMIT_REF_NAME
  needs:
    - build-python3.9
    - build-python3.8
    - build-python3.7
    - build-python3.6
  trigger:
    project: mocasin/mocasin-maps-examples
    strategy: depend

test-fivegsim:
  stage: plugins
  variables:
    MOCASIN_BRANCH: $CI_COMMIT_REF_NAME
  needs:
    - build-python3.9
    - build-python3.8
    - build-python3.7
    - build-python3.6
  trigger:
    project: mocasin/fivegsim
    strategy: depend

check-formatting:
  stage: test
  image: python:3.8
  tags:
    - python3.8
  needs: []
  script:
    - pip install black
    - black --check .
