hydra:
  sweep:
    dir: multirun/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.job.num}_${hydra.job.override_dirname}

log_level : WARNING

defaults:
  - hydra/job_logging: pykpn
  - representation: SimpleVector
  - platform: default
  - kpn: default
  - mapping: default
  - trace: default
  - slx: "2017_10"
  - tgff: default
  - task: ???
