hydra:
  sweep:
    dir: multirun/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.job.num}_${hydra.job.override_dirname}

log_level : WARNING

defaults:
  - source: slx
  - representation: SimpleVector
  - platform: invalid
  - task: random_walk_mapping
  - hydra/job_logging: pykpn
  - mapping: random_mapping
  - trace: ${defaults.0.source}/default
  - tgff: default
  - kpn: invalid
  # allow external configurations to append any configurations
  - append: default
