platform:
        type: 'bus'
        class: pykpn.tgff.tgffSimulation.PlatformFromTgff
        params:
                platform_type: ${platform.type}
                processor: 'PROC_0'
                file_path: ${tgff.directory}/${tgff.file}
                amount: 2
