# @package _group_

_target_: pykpn.tetris.scheduler.bruteforce_memo.BruteforceMemoScheduler

# Dump the status of the queue every N steps
bf_dump_steps: 1000

# Dump the mem table
dump_mem_table: false

