# @package _group_

_target_: pykpn.tetris.scheduler.bruteforce.BruteforceScheduler

# Dump the status of the queue every N steps
bf_dump_steps: 1000

memoization: false

# Dump the mem table
dump_mem_table: false

