# @package _group_

_target_: pykpn.tetris.scheduler.wwt15.WWT15Scheduler
params:
        name: WW15Scheduler
# A high-level mapper algorithm: segmentized (SEG), joint-fixed (JF),
# joint-dynamic (JD)
# wwt15_type: SEG

# Determines an order, in which applications are mapped.
# Options: COST, DEADLINE, CDP.
wwt15_sorting: COST

# In segmentizes version, which points might form the segment: all points (ALL),
# or only best (if possible, not to violate deadlines) (BEST)
wwt15_seg_explore: ALL

# Enable constraints in Lagrangian relaxation solver:
# constaint on resources (R), on delay (D), on resource-delay-product (RDP).
wwt15_lr: []

# Number of iterations (rounds) in Lagrangian relaxation
wwt15_lr_rounds: 1000
