hydra:
  sweep:
    dir: multirun/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.job.num}_${hydra.job.override_dirname}

log_level : WARNING

defaults:
  - representation : SimpleVector
  - platform: exynos
  - task: random_walk_mapping
  - hydra/job_logging: pykpn
  - kpn: audio_filter
  - mapping: default
  - trace: default
