hydra:
  sweep:
    dir: multirun/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.job.num}_${hydra.job.override_dirname}

log_level : WARNING

defaults:
  - source: slx
  - representation: SimpleVector
  - platform: ${defaults.0.source}/default
  - task: random_walk_mapping
  - hydra/job_logging: pykpn
  - kpn: ${defaults.0.source}/default
  - mapping:
          mapper: random_mapping
  - trace: ${defaults.0.source}/default
  - tgff: default
