hydra:
  sweep:
    dir: multirun/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${hydra.job.num} #_${hydra.job.override_dirname}
    config:
      override_dirname:
        exclude_keys : ['mapping','mapper','mapping/mapper'] #TODO need to fix this!

log_level : WARNING

defaults:
  - source: slx
  - representation: SimpleVector
  - platform: ${defaults.0.source}/default
  - task: random_walk_mapping
  - hydra/job_logging: pykpn
  - kpn: ${defaults.0.source}/default
  - mapping: default
  - mapping/mapper: default
  - trace: ${defaults.0.source}/default
  - tgff: default
