hydra:
  sweep:
    dir: multirun/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.job.num}_${hydra.job.override_dirname}

log_level : WARNING

defaults:
  - type: kpn
  - representation: SimpleVector
  - platform: ${defaults.0.type}/default
  - task: ${defaults.0.type}/default
  - hydra/job_logging: pykpn
  - kpn: ${defaults.0.type}/default
  - mapping: random_mapping
  - trace: ${defaults.0.type}/default
  - tgff: default
