# @package _group_
_target_ : pykpn.design_centering.DesignCentering
max_samples : 50
adapt_samples : 10
hitting_probability : [0.4, 0.5, 0.5, 0.7, 0.9]
hitting_probability_threshold : 0.7
deg_p_polynomial : 2
step_width : [0.9, 0.7, 0.6, 0.5, 0.1]
deg_s_polynomial : 2
max_pe : 16
distr : uniform
keep_metrics : True
visualize_mappings : false
record_samples : false
