
_target_: mocasin.tetris.scheduler.bruteforce_memo.BruteforceMemoScheduler

# Reuse previous schedules
schedule_reuse: False

migrations: True
preemptions: True
rotations: False

# Dump the status of the queue every N steps
bf_dump_steps: 1000

# Dump the mem table
dump_mem_table: false
