# @package _group_
_target_: mocasin.platforms.odroid.DesignerPlatformOdroid
# Once hydra 1.1 rolls out with recursive instantiation,
# we should replace this and recursively instantiate
# the processors. See:
# https://github.com/facebookresearch/hydra/issues/566
processor_0:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type : 'proc_type_0'
  frequency : 1500000000
  static_power: 0.1403
  dynamic_power: 0.3202
processor_1:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type : 'proc_type_1'
  frequency : 1800000000
  static_power: 0.2148
  dynamic_power: 1.3196
num_big : 4
num_little : 4
name: 'exynos'
symmetries_json: null
embedding_json: null
