# @package _group_
_target_: pykpn.mapper.genetic.GeneticMapper
pop_size : 10
num_gens : 5
cxpb : 0.35
mutpb : 0.5
tournsize : 4
mupluslambda: true
initials : random
radius : 5
random_seed: 42
crossover_rate : 1
record_statistics: true
dump_cache: false
chunk_size : 10
progress : true
parallel : true
jobs : 4
objective_exec_time : true
objective_num_resources : true
