# @package _group_

_target_: pykpn.mapper.gradient_descent.GradientDescentMapper
gd_iterations : 20
parallel_points : 5
stepsize : 1
momentum_decay : 0.5
random_seed : 42
record_statistics: true
dump_cache: false
chunk_size : 10
progress : true
parallel : true
jobs : 2
