# @package _group_

_target_: pykpn.mapper.random_walk.RandomWalkMapper
num_iterations : 100
progress :  false
radius : 5.0
random_seed : null
record_statistics: true
parallel : true
dump_cache : false
chunk_size : 10
jobs : 4
