# @package _group_
_target_: pykpn.mapper.tabu_search.TabuSearchMapper
random_seed : 42
record_statistics: true
max_iterations : 10
iteration_size : 5
tabu_tenure : 5
move_set_size :  10
radius : 2
dump_cache: false
chunk_size : 10
progress : true
parallel : true
jobs : 4
