# @package _group_
  name: 'TASK_GRAPH_0'
  file: ${tgff.directory}/${tgff.file}
  _target_: pykpn.tgff.tgffSimulation.KpnGraphFromTgff
  params:
    file_path: ${kpn.file}
    task_graph: ${kpn.name}
