# @package _group_
_target_: pykpn.tgff.tgffSimulation.PlatformFromTgff
platform_type: 'bus'
processor_1: 'processor_0'
processor_2: 'processor_1'
processor_3: 'processor_2'
processor_4: 'processor_3'
tgff_file: ${tgff.directory}/${tgff.file}
