# @package _group_
_target_: pykpn.tgff.tgffSimulation.TraceGeneratorWrapper
tgff_file: ${tgff.directory}/${tgff.file}
graph_name: ${kpn.name}
repetition : 1
processor_types :
  - ${platform.processor_0.type}
  - ${platform.processor_1.type}
  - ${platform.processor_2.type}
  - $platform.processor_3.type}
