# @package _global_
platform:
  name: test
  file: ???
  _target_: mocasin.slx.platform.SlxPlatform
  params:
    name: ${platform.name}
    platform_xml: ${platform.file}

kpn:
  name: ???
  file: ???
  _target_: mocasin.slx.kpn.SlxKpnGraph
  params:
    name: ${kpn.name}
    cpngraph: ${kpn.file}

mapping:
  name: ${kpn.name}_on_${platform.name}
  file: ???
  _target_: mocasin.slx.mapping.SlxMapping
  params:
    mapping_xml: ${mapping.file}

trace:
  directory: ???
  _target_: mocasin.slx.trace.SlxTraceReader
  params:
    trace_dir: ${trace.directory}
    prefix: ${kpn.name}.
