_target_: mocasin.mapper.genetic.GeneticMapper
pop_size : 20
num_gens : 50
cxpb : 0.35
mutpb : 0.5
tournsize : 4
mupluslambda: true
initials : random
radius : 5
random_seed: 42
crossover_rate : 1
record_statistics: true
dump_cache: false
chunk_size : 10
progress : true
parallel : true
jobs : 4
# Supported objectives: exec_time, resources, energy
objectives : ["exec_time", "energy", "resources"]
